// REQUIRES F3+T then /reload

// Hide JEI Items
JEIEvents.hideItems(event => {
    // WTF inv pets, *wtf*
    event.hide('inventorypets:temp_feed_bag');
    event.hide('inventorypets:temp_chest');
    event.hide('inventorypets:temp_double_chest');
    event.hide('inventorypets:temp_sated_chest');
    event.hide('inventorypets:temp_sated_double_chest');
    event.hide('#dapack:disabled_pets');
    event.hide('kubejs:incomplete_ammo'); // hide base one
    event.hide(/creategoggles:.+_backtank_placeable/);

    // hide soph storage clutter with types and tiers (should only show 1 each type and 1 each tier)
    event.hide(/sophisticatedstorage:[a-z]+_barrel$/);
    event.hide(/sophisticatedstorage:[a-z]+_chest$/);
    event.hide(/sophisticatedstorage:[a-z]+_shulker_box$/);
    event.hide(/sophisticatedstorage:limited_[a-z]+_barrel_.$/);
});

// Show JEI Items
JEIEvents.addItems(event => {
    event.add(Item.of('minecraft:bundle'));
    event.add(Item.of('inventorypets:feed_bag', {Damage:0}));
    event.add(Item.of('inventorypets:pet_chest', {Damage:0}));
    event.add(Item.of('inventorypets:pet_double_chest', {Damage:0}));
    event.add(Item.of('inventorypets:pet_sated_chest', {Damage:0}));
    event.add(Item.of('inventorypets:pet_sated_double_chest', {Damage:0}));

    // add back basic soph storage tiers (clutter fix)
    for (const tier of ['copper', 'iron', 'gold', 'diamond', 'netherite']) {
        event.add(Item.of(`sophisticatedstorage:${tier}_barrel`, {woodType:'spruce'}));
        event.add(Item.of(`sophisticatedstorage:${tier}_chest`, {woodType:'oak'}));
        event.add(Item.of(`sophisticatedstorage:${tier}_shulker_box`));
        for (let i=1; i<=4; i++) { event.add(Item.of(`sophisticatedstorage:limited_${tier}_barrel_${i}`, {woodType:'spruce'})); }
    }

    // let ammos = ["ammo9mm", "ammo45acp", "ammo57", "ammo357", "ammo50ae", "ammo46", "ammo545", "ammo556", "ammo68", "ammo762", "ammo12gauge", "doom_50calpistol" ,"ammo762x51" /*,"doom_50calrifle"*/ ,"ammo338lapua" ,"ammo50bmg" ,"doom_plasmacell" ,"hl_rebar"]
    // for (const ammo of ammos) { // not functional to cheat in, just for recipe searching
    //     let name = Item.of('pointblank:'+ammo).item.getDescription().getString()
    //     event.add(Item.of('kubejs:incomplete_ammo',`{display:{Name:'{"text":"Incomplete Ammo (${name})","italic":false}',Lore:['{"text":"Ammo: ${name}","color":"gray","italic":false}']}}`))
    // }
});

// Info is the desc tab ℹ️
JEIEvents.information(event => {

    // Things produced by a machine that lack proper JEI recipe display
    event.addFluid('ad_astra:cryo_fuel', [
        Text.of('Generated from ice materials in the ')
        .append(Text.of('Cryo Freezer').aqua())
    ] );

    event.addFluid('mekanismscience:seawater', [
        Text.of('Generated in ocean biomes by the ')
        .append(Text.of('Seawater Pump').aqua())
        .append(' when submerged')
    ] );

    event.addFluid('mekanismscience:compressed_air', [
        Text.of('Generated by the \n')
        .append(Text.of('Air Compressor').aqua())
        .append(' in gas form')
    ] ); // Note: should be the gas version with .addForType()
})